CREATE TABLE IF NOT EXISTS films
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR      NOT NULL CHECK (name != ''),
    description VARCHAR(200) NOT NULL CHECK (description != ''),
    releaseDate DATE,
    duration    INT          NOT NULL CHECK (duration > 0)
);
CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR NOT NULL,
    login    VARCHAR NOT NULL CHECK (login != ''),
    name     VARCHAR,
    birthday DATE
);
CREATE TABLE IF NOT EXISTS genre
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS rating
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  BIGINT REFERENCES films (id),
    genre_id BIGINT REFERENCES genre (id),
    UNIQUE (film_id, genre_id)
);
CREATE TABLE IF NOT EXISTS film_likes
(
    film_id  BIGINT REFERENCES films (id),
    user_id BIGINT REFERENCES users (id),
    UNIQUE (film_id, user_id)
);
CREATE TABLE IF NOT EXISTS film_rating
(
    film_id BIGINT REFERENCES films (id),
    rating_id BIGINT REFERENCES rating (id),
    UNIQUE (film_id)
);
CREATE TABLE IF NOT EXISTS friends
(
    id        BIGINT REFERENCES users (id),
    friend_id BIGINT REFERENCES users (id),
    status    BOOLEAN,
    UNIQUE (id, friend_id)
);